### ISSUE TITLE
The Old JS Libraries

### ISSUE THREAD

**Issue by rayk** [frankpepermans/rxdart#3]
Hi Frank...

I checking you native implementation.... I nice and certainly cleaner in some ways without all the JS wrapping. 

I just wanted to drop you a line to try to understand, if you had any issues to with 0.6.0 interop. 

I am middle to move some JS stuff to Dart and mostly not a problem. Except promises. I know +jacob richman is working to harmonise Futures/Await and promises. 

My real question is did you come across something that made you want to dump the wrapping.... or was it case of native Async Observable was cleaner approach....

Thanks in advance, hope the question is not too fluffy..

**Comment by frankpepermans** [comment]
Hey there,

Don't worry too much, the main reason to step away from the JS version, is to open up the library for server (or soon Flutter use) as well.

That said, I did have some issues before, but nothing that couldn't be worked around:

- operator overloads: often used in JS land, just check the argument's type at runtime and do different things, sure you could type arguments as dynamic in Dart and just do the same, but I'm no fan of this.
Here union types would be very helpful, I worked around by just creating multiple functions for each supported argument type in Dart land.

- rest arguments, again no go in Dart, rxjs merge allows you to pass n amount of Streams, in Dart I went with using a List<Stream> instead, and using the old context interop way to call Function.apply on the JS side.

- having to use allowInterop is very annoying, I did my very best to hide that, allow Dart users to just pass methods as-is, and wrap in allowInterop within the library code before going to the JS side.

- I opened a ticket because some functions I ported did run fine with Dartium and the Dart VM, but failed after dart2js. As a workaround I again just used the old context way as I'm sure it will be fixed at some point later.

So again, this move is mainly to have rxdart working everywhere, not just in a browser :)
